# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d9aad061bb9a1102794868ef507bcc42b2997ad00bae855a0941f7197b8644038566550d5870e1f097e2cfde8a111e139c51f5fde73a26c03a7353de856a925

test:
  secret_key_base: 0f8ad4e6413564f409129f4a7439ada4df5a968146cbd6b4471e01c2878cb984318cafd727a0ffbb38aaf328d4538e719f2bb4d2a28c935371ffb2812a740624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
